### PR TITLE
Kuka online

### PR DESCRIPTION
**Pull request by Arastookhajehee**
Adding KUKA robot support.

### CODE REVIEW

**Comment by garciadelcastillo** [comment]
This is awesome, thank you @Arastookhajehee !!! 🤖💪🤓

**Comment by Arastookhajehee** [comment]
@garciadelcastillo Hi Jose Luis,
I'm wondering if this code was merged into the main repo.
It seems the code is still not updated in either the KUKA-online or the main branch.

**Comment by garciadelcastillo** [comment]
Hi @Arastookhajehee ! 

This was already merged into [RobotExMachina:kuka-online](https://github.com/RobotExMachina/Machina.NET/tree/kuka-online), did you intend to merge into `main`?

**Comment by Arastookhajehee** [comment]
Hi @garciadelcastillo 
It seems a bit complicated which files were in the previous PR I made a while ago.
The new PR I just made to merge into the main branch should be the correct set of files.

**Pull request merged**
